Resources/config.xml
Shows error message when 404 is returned from Test button. This means the plugin is not active.
-> Was actually already implemented this way, but badly.
- Click test button before plugin is activated
**Fixed issue**:  #22 PW-2743
=> Fix #22 PW-2743 Show error on 404

Components/Payload/Providers/ShopperInfoProvider.php
The billing number is removed and the houseNumber field is now empty. Because Shopware saves the street and house number in the same field it's not possible to separate those values as indicated in the documentation:
https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v49/payments__reqParam_billingAddress
Customer ID is not be included in the address fields
**Fixed issue**:  PW-2603
=> PW-2603 remove customer id from shopperinfo payload

Components/PaymentMethodService.php
Since the PM code is being used to fetch the logo image some methods show a broken logo. A constant array was introduced to maintain multiple PMs with this condition.
Yandex Money shows logo.
**Fixed issue**:  PW-2862
=> [PW-2862] Fixing Yandex logo

Components/NotificationProcessor/OfferClosed.php, Components/PaymentStatusUpdate.php, Models/Event.php, Resources/services/components.xml
Adds notification processor for OFFER_CLOSED notification. It changes the order state to cancelled/rejected and the payment state to 'this process has been cancelled'.
Receive offer_closed notification.
**Fixed issue**:  #15
=> Fixes #15 Handle offer_closed notification

Controllers/Backend/TestAdyenApi.php
Catch error in Test button controller and show error message instead of 'real' crash.
Test button without valid URL prefix.
**Fixed issue**:  #18 PW-2600
=> Fixes #18 PW-2600 Catch exception during backend Test

Components/BasketService.php, Models/Event.php
Adds an Adyen_Basket_RestoreFromOrder event that is triggered when a payment is cancelled and the basket has to be rebuild from the previous order.
It is not possible to copy custom fields from the old order to a new basket, so this event provides an entry point for other developers to do their magic.
**Fixed issue**:  #13 PW-2748
=> Fixes #13 PW-2748 Add event to order restore

AdyenPayment.php, Components/OrderMailService.php, Controllers/Frontend/Adyen.php, Controllers/Frontend/Process.php, Models/PaymentInfo.php, Resources/services/components.xml, Resources/services/subscribers.xml, Subscriber/OrderEmailSubscriber.php, plugin.xml
Disabled sending email before payment and sends it when payment is succesfull.
Payment with CC: failed, success
Paymetn with sofort: failed, success
**Fixed issue**:  #12
=> Only send mail after succesful payment

Components/Payload/Providers/ApplicationInfoProvider.php, Components/Payload/Providers/OrderInfoProvider.php
The SameSite cookie security feature being rolled out by browsers breaks the session on 3DS1 auth redirecting back to the shop.
Using Adyen's `redirectFromIssuerMethod=GET`, `redirectToIssuerMethod=POST` and `returnUrl` parameters on the `/payments` request would avoid a redirect back using POST.
Data added to payment request 
**Fixed issue**:  #51
=> add redirect  data to payments request

Resources/frontend/js/jquery.adyen-payment-selection.js
This pull request adds the Gift Card implementation for payment methods.
* Giftcards:
* Givex gift card
* SVS gift card
* ValueLink gift card
* generic gift card
Card numbers as described on: https://docs.adyen.com/development-resources/test-cards/test-card-numbers#gift-cards
**Fixed issue**: #66   
**Note**:
The Gift Card PIN can be optional.  
The field will only be shown in the UI, when the gift card detail property `encryptedSecurityCode.optional` is `false` (see below example). In all other cases if the field is not present or optional is true, the PIN field will be omitted.
```bash
{
...
"details": [
{
"key": "encryptedCardNumber",
"type": "cardToken"
},
{
"key": "encryptedSecurityCode",
"optional": false,
"type": "cardToken"
},
...
],
"name": "SVS",
"supportsRecurring": true, …
```
=> Ap 59 gift card

Components/OrderMailService.php, Controllers/Frontend/Adyen.php, Subscriber/OrderEmailSubscriber.php
Update to disable sending an e-mail when payment is rejected.
Payment cards:  
(tested with invalid CVC as well as noted in the comments)
* Credit card
* Sofort 
**Fixed issue**: #46
=> AP-46 update mail sending

Components/Configuration.php
We added a fallback in case the shop is not set. When no shop is set when retrieving configuration the configuration of the current shop be returned.  
Retrieve correct Merchant account when no shop is set.
**Fixed issue**:  #70
=> #70 add fallback when no shop is specified

Resources/frontend/js/jquery.adyen-confirm-order.js
Bancontact mobile payment option added, as per documentation, to the available payments.
For the api v52 payment method:  bcmc_mobile_QR and bcmc_mobile_app are provided and passed to the Adyen checkout web component.
The code has also been verified to be able to work with api v64.
One issue arose: for bcmc_mobile_QR, 
On the test account for payment returned the response: `Could not find an acquirerAccount`.
**Fixed issue**: #58
=> AP-58 Enable Mobile bancontact payments

Resources/frontend/js/jquery.adyen-payment-selection.js
Added a more strict selector to the payment submit button. This selector doesn't conflict with the default language switcher.
Proceed button works as expected
**Fixed issue**:  #86
=> #86 more strict paymentMethodFormSubmitSelector

Components/Configuration.php
In some contexts (backend, cron, etc) there's no Shop service available. We're enclosing the service getter in a try/catch block so the Test API button in the backend uses the default null as Shop.
Test button functions properly.
Frontend API calls use the Shop context.
**Fixed issue**:  PW-3544
=> [PW-3544] try/catch block for getting the Shop service from the backend

Controllers/Frontend/Transparent.php, Resources/views/frontend/transparent/redirect.tpl
Paypal uses the GET parameter `payload` and Klarna uses `redirectResult`, here they are being added to the transparent redirect so they can be forwarded to the return controller.
Paypal, Klarna and 3DS1 payments.
**Fixed issue**:  PW-3546, PW-3561
=> [PW-3546] Adding payload and redirectResult GET parameters to transparent redirect

Resources/views/frontend/checkout/adyen_libaries.tpl
Update the Web components library to a higher version compatible with Adyen API v51.
The issue occurs Adyen.js library conflicts with other js libraries used in Shopware.
The upgraded version should resolve these issue's, although it should be tested by the reporters as well to make sure.
Ideal web components should be upgrade to the latest version, but this needs to be implement after or during [#62 Upgrade Checkout API to v64]
* Verify listed payments on checkout and web component interaction.
* Payment flow with credit card.
**Fixed issue**:  #84
=> ASW-251 #84 bump Web Components to 3.12.1 highest compatible API v51

Components/Payload/Providers/ApplicationInfoProvider.php
Add the merchantReference (order number of shopware) to the returnUrl.
Adyen backend will set this query parameter as well, if the parameter exists it will be overwritten.
So that the merchantReference will always be present ont the return Url's.
**Fixed issue**:  #13
=> ASW-226 #13 Add merchantReference of order number on returnUrl

Components/Adyen/ApiFactory.php, Components/Adyen/OriginKeysService.php, Components/Adyen/PaymentMethodService.php, Components/Adyen/RefundService.php, Components/OriginKeysService.php, Resources/services/components.xml
All storefronts (=shops) of the same Shopware instance would use the main shop's API key 
and Merchant account for accessing Payments API.
Additionally also the Main shop credentials where used to configure the origin_key.
1. Codebase has been adjusted that each apiClient is constructed with their corresponding 
storefront API key and Merchant account (set in the plugin configuration).
1. Each storefront now stores their own generated origin_key (generation is done by Adyen CheckoutUtility).
Setup:
* Adyen Account with multiple merchant accounts (named M1 & M2)
* Shopware instance with multiple storefronts (A & B)
Setup Shopware shop with multiple storefronts:
* Test storefront A, merchant M1: payment BCMC and 3DS :heavy_check_mark: 
* Test storefront A, merchant M1: with Credit Card …
=> Ap 103 second shop cannot decrypt api data

Components/IncomingNotificationManager.php, Controllers/Frontend/Notification.php, Exceptions/AuthorizationException.php, Exceptions/InvalidAuthenticationException.php, Exceptions/InvalidHmacException.php, Http/Response/NotificationResponseFactory.php, Http/Validator/Notification/AuthenticationValidator.php, Http/Validator/Notification/Chain.php, Http/Validator/Notification/HmacValidator.php, Http/Validator/Notification/LoggingAuthorizationValidatorDecorator.php, Http/Validator/Notification/NotificationValidatorInterface.php, Resources/services.xml, Resources/services/adyen.xml, Resources/services/managers.xml, Resources/services/validators.xml
**Responses on incoming notification:**
* process Authentication, on failure return failed message (HTTP 401)
* process HmacKey, on failure return failed message (HTTP 401)
* all other notifications sent response '[accepted]' (HTTP 202)
* use unified way to create JsonResponse with status code (aligned responses with docs and SW 6 Plugin)
* refactor Validation to chained validation
**Processing notification:**
* skip report notification
Test cases:
* Missing Authentication exception handling
* Invalid Authentication exception handling
* Missing Hmac key exception handling
* Invalid Hmac key exception handling
* Skip Report notification
**Fixed issue**:  #111
=> Ap 257 notifcations reponse

AdyenPayment.php, Components/Manager/AdyenManager.php, Controllers/Frontend/Adyen.php, Controllers/Frontend/Process.php, Controllers/Frontend/Transparent.php, Models/PaymentInfo.php, Resources/frontend/js/jquery.adyen-confirm-order.js, Utils/RequestDataFormatter.php
Store payment data in DB (session has data loss)
Update 3DS2 for payment data handling
Update 3DS1 payment/details data handling parameter mismatch for request
* 3DS1: Mastercard Kredikarte (scheme)
* Enrolled card: Mastercard Kredikarte (scheme)
* Enrolled card: Maestro Kredikarte (scheme)
* Card not enrolled: Visa Kredikarte (scheme)
* 3DS2:
* Fingerprint Mastercard Kredikarte (scheme)
* ChallengeShopper: Visa Kredikarte (scheme)
* Frictionless: Visa Kredikarte (scheme)
**Fixed issue**:  #108
=> Ap 256 payment data missing

AdyenPayment.php, Components/FifoTextNotificationLoader.php, Components/IncomingNotificationManager.php, Components/TextNotificationManager.php, Controllers/Frontend/Notification.php, Models/Feedback/TextNotificationItemFeedback.php, Models/TextNotification.php, Resources/services/adyen.xml, Resources/services/components.xml, Resources/services/cronjobs.xml, Resources/services/managers.xml, Subscriber/Cronjob/ProcessNotifications.php
When notifications are received ideally no extra logic is done other than storing them in the database after the authentication methods have been verified. With this PR we're saving the incoming notifications AS IS in a new database entity. On cron job run they are converted and stored as a regular notification to be processed.
After the authentication is valid incoming notifications are received successfully regardless of content, and stored in a new table `s_plugin_adyen_text_notification`.
On cron job run the text notifications stored are fetched, converted into regular notifications in `s_plugin_adyen_order_notification` and processed.
**Fixed issue**: #81
=> Store incoming notifications in new DB entity with no extra logic

AdyenPayment.php, Controllers/Frontend/Adyen.php, Models/PaymentInfo.php, Subscriber/OrderEmailSubscriber.php
The `Shopware_Modules_Order_SendMail_Send` event is used to store the mail variables in the PaymentInfo entity to be used in the delayed mail sending process, but this event doesn't always contain the `orderId` as the order save process hasn't finished.
A fallback to the ordernumber is being added using the `adyenPaymentInfoId` session key and the `Shopware_Modules_Order_SaveOrder_ProcessDetails` event to save the ordernumber in the PaymentInfo.
After placing an order the mail variables are stored in PaymentInfo.
**Fixed issue**: PW-3959
=> [PW-3959] Using 'ordernumber' to fetch order mail variables

Resources/frontend/js/jquery.adyen-confirm-order.js, Resources/views/frontend/checkout/adyen_configuration.tpl, Resources/views/frontend/checkout/change_payment.tpl, Resources/views/frontend/checkout/confirm.tpl, Subscriber/CheckoutSubscriber.php
When there's a payment method selected and no initialization of the Adyen config in the session the order can't be placed. In this PR a fallback to the data provided by the CheckoutSubscriber is introduced.
Successful payment with Paypal -> New payment with payment method preselected
**Fixed issue**:  PW-3933
=> [PW-3933] Getting Adyen config data from the CheckoutSubscriber if not present in the session storage

Resources/views/frontend/checkout/change_payment.tpl, Serializer/Payment/PaymentMethodSerializer.php
Showpare 5 uses internally `array<int, array>` structure to identify Payment Methods
Updated the paymentMehtods serializer to implement SW5 list and add additional parameter for identifying stored payments.
Split up payments on selection template based on parameter.
Shipping methods are available again for enabled country and Adyen payment methods.
Shipping methods are listed below default payments.
Test cases:
* :heavy_check_mark: default payment
* :heavy_check_mark: stored payment
* :warning: shipping method, issue during reset of payment option (see ticket: #126, not in scope of current ticket)
**Fixed issue**:  #124
=> AP-266 merge all payment methods in one array and filter in template

Resources/frontend/js/jquery.adyen-payment-selection.js, composer.json
Fix payment data (browser storage) lost when selecting a shipping method.
Note: when selecting a shipping method, the payment data needs to be re-entered 
_(this was working the same before this change)_
@acampos1916 maybe create a ticket to adjust the working: payment data not lost on selecting a shipping method?
Due note that currently Shopware is handling the shipping selection with an ajax call and replacing the form, 
it could be complex to alter the current working.
Test cases:
* select Credit card, select shipping method (data needs to stay as is)
* select Credit Card, selecting non-adyen payment method (data needs to be cleared)
* select Credit Card, select another adyen payment method  (data needs to update to new state)
* complete payment flow
Explicit test on Shopware version …
=> AP-268 fix issue on selecting shipping method

Subscriber/CheckoutSubscriber.php
If a user has no preselected adyen payment an error occurs:
But Method fetchByTypeOrId() doesn't allow null values. 
Set s_user_attributes.adyen_payment_payment_method to NULL or create a new User and go to the checkout.
=> Catch user that has no adyen payment preselected

Resources/frontend/less/all.less, Resources/views/frontend/checkout/change_payment.tpl
In the payment selection page Adyen lists both regular and stored payment methods with the same style as the Shopware title. In this PR an indentation is being introduced to differentiate the sections and the titles are only shown only if both groups are present.
Only stored PMs or only regular PMs: hides the title.
Both stored PMs and regular PMs are present: both titles are shown with indentation.
**Fixed issue**:  PW-4128
=> [PW-4128] Hiding PM and Stored PM group title if the other group is empty

Components/Builder/NotificationBuilder.php, Components/IncomingNotificationManager.php, Components/NotificationManager.php, Models/Notification.php
OFFER_CLOSED and AUTHORISATION notification with success=false should be processed after awhile
This PR introduces a new column to indicate when a notification should be processed, 
adds `where` clause to use the processing time, where available, in selecting next notifications for processing.
**Fixed issue**:  #141
=> [PW-4149] add processing time to notifications

Components/Builder/NotificationBuilder.php, Components/Configuration.php, Components/NotificationProcessor/ManualReviewAccept.php, Components/NotificationProcessor/ManualReviewReject.php, Resources/config.xml, Resources/services/components.xml
If a payment is sent to Adyen's Case Management and is rejected or accepted a webhook will be sent (if enabled for the risk profile).
MANUAL_REVIEW_ACCEPT won't perform any logic as the payment is being processed by the regular notification flow. MANUAL_REVIEW_REJECT will cancel the order if the config is set to Cancel. The config matches the documentation for Case Management modifications https://docs.adyen.com/risk-management/case-management#modifications
* Config set to Cancel:
* Process MANUAL_REVIEW_REJECT notification: cancels the order.
* Process MANUAL_REVIEW_ACCEPT notification: N/A.
* Config set to None:
* Process MANUAL_REVIEW_REJECT notification: N/A.
* Process MANUAL_REVIEW_ACCEPT notification: N/A.
**Fixed issue**:  PW-4165
=> [PW-4165] Support for MANUAL_REVIEW_ACCEPT and MANUAL_REVIEW_REJECT notifications

Components/Manager/OrderManager.php, Components/Manager/OrderManagerInterface.php, Controllers/Frontend/Process.php, Resources/services/managers.xml, Resources/services/subscribers.xml, Subscriber/Cronjob/ProcessNotifications.php, Subscriber/Notification/UpdateOrderPsPSubscriber.php
* Updated authorization success notification to set pspReference on success.
* Unified the pspReference updating process in the plugin
* Authorization success notification  (coming from Adyen)
* return process when making Paypall payment
**Fixed issue**:  #122
=> Ap 264 add psp reference on authorization success notification

.github/CODEOWNERS, Components/PaymentMethodService.php, Resources/frontend/js/jquery.adyen-confirm-order.js, Subscriber/CheckoutSubscriber.php, Subscriber/PaymentSubscriber.php
From issue #139 
This PR hides Adyen payment methods when the total amount in the basket is 0.
Resets the selected payment method to the shopware5 default when the amount has changed, e.g after applying a voucher.
Pay for item that costs nothing
Apply voucher that sets total price to 0
**Fixed issue**:  #139
=> PW-4139 Hide Adyen payment methods for 0 amount transactions

Controllers/Backend/AdyenPaymentNotificationsListingExtension.php, Resources/views/backend/adyen_payment_order/view/detail/transaction_details.js, Resources/views/backend/adyen_payment_order/view/detail/window.js
If an order has been processed with Adyen Payment Methods a new tab will show in the order details. Here it is being renamed to Adyen Notifications and now shows all notifications, not only the ones with status!=handled.
The tab now will always be shown for consistency, but disabled if no transaction is found (not an Adyen PM or no notification has been received).
Orders show the tab regardless of PM, but enabled only for Adyen PM with notifications.
All notifications are shown regardless of status.
**Fixed issue**:  PW-4216
=> [PW-4216] Showing all notifications in order details

Components/NotificationManager.php
The first where clause to fetch the notifications to process was being replaced by the second one.
Processing notifications uses all 3 bound parameters.
**Fixed issue**:  N/A
=> Adding second notification where clause as andWhere

Controllers/Frontend/Process.php
We use Shopware 5.6.8 and had a problem that after every order the user gets correctly redirected to the checkout confirm page but with the notice that the cart is empty. The order itself and the adyen transaction works fine but the user didn't get the correct confirm page displayed.
The problem is that the Shopware Frontend Checkout Controller requires the `sUniqueID` parameter which is in the order entity in the `Process` Controller of the adyen plugin implementation. I've just provided the parameter to the redirect and everything works as expected.
Use showpare 5.6.8
**Fixed issue**:
=> Implement needed sUniqueID for Checkout finish page

Components/BasketService.php, Components/OrderMailService.php, Subscriber/OrderEmailSubscriber.php
Changing cancelAndRestoreByOrderNumber arg type to string
Redirect and non-redirect payments.
**Fixed issue**:  PW-3963
=> [PW-3963] Changing cancelAndRestoreByOrderNumber arg type to string

Resources/frontend/js/jquery.adyen-payment-selection.js
* Update payment selection screen, verify  payment data selected stays stored in Session storage.
* When selecting a shipping method, validate if an active payment method is available.   
if payment data is available do not reset the payment web component screen (show update info button)
* Show the "update info" button when active payment data is available, 
before it would  show an empty web component card for the payment option.
:no_entry: **Current Adyen development branch has a breaking change:**
:no_entry: updated development branch has an additional issue with me.opts.adyenIsAdyenPayment coming from BE.
```js
// file:  Resources/frontend/js/jquery.adyen-confirm-order.js
checkSetSession: function () {
if (!$.isEmptyObject(me.opts.adyenSetSession)) {
//      ...  
} else { …
```
=> AP-269 keep payment after shipping selection, add update info button

Http/Validator/Notification/AuthenticationValidator.php
Our Apache2 in CGI Mode with PHP-FPM uses HTTP_PHP_AUTH_USER instead of PHP_AUTH_USER. We want this plugin to also check the header after checking PHP_AUTH_USER.
=> Update AuthenticationValidator.php to also support Apache CGI Mode Headers

Models/Notification.php
Some textNotifications might not have a paymentMethod object, and when these are converted into notifications a DB exception stops the whole queue. Here the paymentMethod column is being made nullable.
TODO A better flow and error handling can be implemented in the conversion to also avoid the bottlenecks for different kinds of exceptions.
Processing CAPTURE notifications with no paymentMethod object doesn't stop the notification convert loop.
**Fixed issue**:  
PW-4228
Fixes #145
=> [PW-4228] Making the notification's paymentMethod column nullable

Components/BasketService.php
After failed payments the basket line item's article number was not being restored. The column in Shopware's `s_order_basket` table is called `ordernumber`, but this holds the article number.
One and multiple failed payments before a successful payment restores the basket line item with the article number
**Fixed issue**:  NA
=> Restoring article order number to the basket after failed payment

Components/PaymentMethodService.php
When the shopper has no rows in the `s_user_attributes` table the function responsible for updating the payment method selection fails. Here a check is introduced to either perform an insert or an update.
Payment method selection with and without `s_user_attributes` for that user is successfully saved.
**Fixed issue**: PW-4602 fixes #41
=> [PW-4602] Inserting payment method selection as user attribute if no user attribute exists

Models/Notification.php
We can see the below log/issue if the errorDetails key is null in the notification (which can happen with PayPal):
```
array (
'error' => 'An exception occurred while executing \'INSERT INTO s_plugin_adyen_order_notification (order_id, psp_reference, created_at, updated_at, status, paymentMethod, event_code, success, merchant_account_code, amount_value, amount_currency, error_details) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\' with params [171, "155xxxx075", "2021-05-21 13:45:01", "2021-05-21 13:45:01", "received", "paypal", "CAPTURE", 1, "XXX", 4417, "EUR", null]:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column \'error_details\' cannot be null',
)
```
=> [PW-4723] Make error_details column nullable for Shopware 5 notification

Controllers/Frontend/Adyen.php, Resources/frontend/js/jquery.adyen-confirm-order.js, Resources/frontend/less/all.less
Payment methods that returned Pending and a QR code action (like bcmc_mobile/Payconiq) successfully created the component but were not mounting it so that the code could be shown. Here these result codes are being combined with the handling of IdentifyShopper, ChallengeShopper. The component will take care of the appropriate action.
Happy and unhappy flows for bcmc_mobile/Payconiq, 3DS1, 3DS2, iDeal.
**Fixed issue**:  PW-5047
=> [PW-5047] Handle IdentifyShopper, ChallengeShopper, Pending and RedirectShopper with the same createFromAction

Subscriber/CheckoutSubscriber.php
We had Problems getting Google Pay to work. We debugged the code and saw that the Environment-Check is wrong. 
`$this->configuration->getEnvironment()` (see below) will **always** return a lowercased value, because of the constants refering to https://github.com/Adyen/adyen-php-api-library/blob/develop/src/Adyen/Environment.php are lowercased
```
/**
* @param bool $shop
* @return string
*/
public function getEnvironment($shop = false, $lowercase = false): string
{
$environment = Environment::TEST;
if ($this->getConfig('environment', $shop) === self::ENV_LIVE) {
$environment = Environment::LIVE;
}
if ($lowercase) {
return strtolower($environment);
}
return $environment;
}
```
Tested on production Environment, checking the data-adyenGoogleConfig will show PRODUCTION Environment including …
=> Fix GooglePay

Components/Configuration.php, Subscriber/CheckoutSubscriber.php
`\AdyenPayment\Components\Configuration::getEnvironment` was always returning lowercase environment anyway since it returns the constants from `\Adyen\Environment`.
This PR uses lowercase constants for environment variables in `\AdyenPayment\Components\Configuration` to align with the php lib and also fix the issue reported in #179. 
**Fixed issue**: #179
=> Fix env constants
